/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW.mainFrame;

import VIEW.productViews.DeleteUpdateProducts;
import VIEW.userViews.DeleteUpdateUser;
import VIEW.userViews.InsertUser;
import VIEW.userViews.SearchUser;
import VIEW.productViews.InsertProducts;
import VIEW.productViews.SearchProducts;
import VIEW.requests.RequestForm;
import javax.swing.JOptionPane;
/**
 *
 * @author Rafael
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        desktop = new javax.swing.JDesktopPane();
        lblUser = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        Menubar = new javax.swing.JMenuBar();
        MenMat = new javax.swing.JMenu();
        MenProdSearch = new javax.swing.JMenuItem();
        MenProdInset = new javax.swing.JMenuItem();
        MenProdUpdate = new javax.swing.JMenuItem();
        MenRequest = new javax.swing.JMenu();
        MenReqGenerate = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menOpções = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();
        menLogout = new javax.swing.JMenuItem();
        MenManeger = new javax.swing.JMenu();
        MenInsertUser = new javax.swing.JMenuItem();
        MenSearchUser = new javax.swing.JMenuItem();
        MenOpcUpd = new javax.swing.JMenuItem();

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MCK WAREHOUSE MANAGEMENT");

        desktop.setPreferredSize(new java.awt.Dimension(1100, 720));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        lblUser.setText("Usuario: ");

        MenMat.setText("Products");
        MenMat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenProdSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        MenProdSearch.setText("Search");
        MenProdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenProdSearchActionPerformed(evt);
            }
        });
        MenMat.add(MenProdSearch);

        MenProdInset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        MenProdInset.setText("Insert");
        MenProdInset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenProdInsetActionPerformed(evt);
            }
        });
        MenMat.add(MenProdInset);

        MenProdUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        MenProdUpdate.setText("Update/Delete");
        MenProdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenProdUpdateActionPerformed(evt);
            }
        });
        MenMat.add(MenProdUpdate);

        Menubar.add(MenMat);
        MenMat.getAccessibleContext().setAccessibleDescription("");

        MenRequest.setText("Requests");

        MenReqGenerate.setText("Generate");
        MenReqGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenReqGenerateActionPerformed(evt);
            }
        });
        MenRequest.add(MenReqGenerate);

        jMenuItem2.setText("Consult");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenRequest.add(jMenuItem2);

        Menubar.add(MenRequest);

        jMenu3.setText("Recebimentos ");

        jMenuItem3.setText("Gerar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Consultar");
        jMenu3.add(jMenuItem4);

        Menubar.add(jMenu3);

        menOpções.setText("Opções ");

        jMenuItem5.setText("Exportar banco de dados");
        menOpções.add(jMenuItem5);

        menSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        menOpções.add(menSair);

        menLogout.setText("Logout");
        menLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLogoutActionPerformed(evt);
            }
        });
        menOpções.add(menLogout);

        MenManeger.setText("Gerenciar usuarios");
        MenManeger.setEnabled(false);

        MenInsertUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        MenInsertUser.setText("Insert");
        MenInsertUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenInsertUserActionPerformed(evt);
            }
        });
        MenManeger.add(MenInsertUser);

        MenSearchUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenSearchUser.setText("Search");
        MenSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSearchUserActionPerformed(evt);
            }
        });
        MenManeger.add(MenSearchUser);

        MenOpcUpd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MenOpcUpd.setText("Update/Delete");
        MenOpcUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcUpdActionPerformed(evt);
            }
        });
        MenManeger.add(MenOpcUpd);

        menOpções.add(MenManeger);

        Menubar.add(menOpções);

        setJMenuBar(Menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenProdInsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenProdInsetActionPerformed
        InsertProducts insertproducts = new InsertProducts();
        insertproducts.setVisible(true);
        desktop.add(insertproducts);

    }//GEN-LAST:event_MenProdInsetActionPerformed

    private void MenSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSearchUserActionPerformed
        SearchUser searchuser = new SearchUser();
        searchuser.setVisible(true);
        desktop.add(searchuser);

    }//GEN-LAST:event_MenSearchUserActionPerformed

    private void MenOpcUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcUpdActionPerformed
        DeleteUpdateUser deleteuser = new DeleteUpdateUser();
        deleteuser.setVisible(true);
        desktop.add(deleteuser);
        
    }//GEN-LAST:event_MenOpcUpdActionPerformed

    private void MenInsertUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenInsertUserActionPerformed
        InsertUser createuser = new InsertUser();
        createuser.setVisible(true);
        desktop.add(createuser);

    }//GEN-LAST:event_MenInsertUserActionPerformed

    private void menLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLogoutActionPerformed
        LoginFrame loginframe = new LoginFrame();
        loginframe.setVisible(true);
        dispose();

    }//GEN-LAST:event_menLogoutActionPerformed

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menSairActionPerformed

    private void MenProdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenProdSearchActionPerformed
        SearchProducts searchproducts = new SearchProducts();
        searchproducts.setVisible(true);
        desktop.add(searchproducts);

    }//GEN-LAST:event_MenProdSearchActionPerformed

    private void MenProdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenProdUpdateActionPerformed
        DeleteUpdateProducts deleteprod = new DeleteUpdateProducts();
        deleteprod.setVisible(true);
        desktop.add(deleteprod);

    }//GEN-LAST:event_MenProdUpdateActionPerformed

    private void MenReqGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenReqGenerateActionPerformed
        RequestForm requestForm = new RequestForm();
        requestForm.setVisible(true);
        desktop.add(requestForm);

    }//GEN-LAST:event_MenReqGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenInsertUser;
    public static javax.swing.JMenu MenManeger;
    private javax.swing.JMenu MenMat;
    private javax.swing.JMenuItem MenOpcUpd;
    private javax.swing.JMenuItem MenProdInset;
    private javax.swing.JMenuItem MenProdSearch;
    private javax.swing.JMenuItem MenProdUpdate;
    private javax.swing.JMenuItem MenReqGenerate;
    private javax.swing.JMenu MenRequest;
    private javax.swing.JMenuItem MenSearchUser;
    private javax.swing.JMenuBar Menubar;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblUser;
    public static javax.swing.JLabel lblUserName;
    private javax.swing.JMenuItem menLogout;
    private javax.swing.JMenu menOpções;
    private javax.swing.JMenuItem menSair;
    // End of variables declaration//GEN-END:variables

}
