/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW.productViews;

import CONTROLER.ProductControler;
import CONTROLER.UserControler;
import MODEL.ProductModel;
import MODEL.UserModel;
import VIEW.MainFrame;
import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rafael
 */
public class DeleteUpdateProducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteUpdateProducts
     */
    public DeleteUpdateProducts() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSaveUpdate = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        btnDeleteProd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        txtProductSearch = new javax.swing.JTextField();
        btnUpdateProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtManufactor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtBarcode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Delete and Update Products");
        setPreferredSize(new java.awt.Dimension(1100, 720));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btnSaveUpdate.setText("SAVE UPDATE");
        btnSaveUpdate.setEnabled(false);
        btnSaveUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUpdateActionPerformed(evt);
            }
        });

        btnClearFields.setText("CLEAR FIELDS");
        btnClearFields.setEnabled(false);
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        btnDeleteProd.setText("DELETE");
        btnDeleteProd.setEnabled(false);
        btnDeleteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProdActionPerformed(evt);
            }
        });

        jLabel5.setText("SELECTED USER ");

        jLabel1.setText("Product:");

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductSearchActionPerformed(evt);
            }
        });
        txtProductSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductSearchKeyReleased(evt);
            }
        });

        btnUpdateProd.setText("UPDATE");
        btnUpdateProd.setEnabled(false);
        btnUpdateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProdActionPerformed(evt);
            }
        });

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSearch.setFocusable(false);
        tblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearch);

        jLabel6.setText("Type");

        jLabel7.setText("Manufactor");

        jLabel8.setText("Barcode");

        jLabel2.setText("Code");

        txtType.setEnabled(false);

        jLabel3.setText("id");

        txtManufactor.setEnabled(false);

        jLabel4.setText("Name");

        txtName.setEnabled(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtBarcode.setEnabled(false);

        jLabel9.setText("Amount");

        txtAmount.setEnabled(false);

        txtId.setEnabled(false);

        txtCode.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(btnRefresh))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtManufactor, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnDeleteProd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearFields)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtManufactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteProd)
                    .addComponent(btnUpdateProd)
                    .addComponent(btnSaveUpdate)
                    .addComponent(btnClearFields))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUpdateActionPerformed
        update();
        clearFields();
        disableButtons();
        disableTxtFields();
        tblSearch.setEnabled(true);
        refresh();
    }//GEN-LAST:event_btnSaveUpdateActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        clearFields();
        disableButtons();
        disableTxtFields();
        tblSearch.setEnabled(true);
        //  cmbPerfil.setEnabled(false);

    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void btnDeleteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProdActionPerformed
        autorizationUser();

    }//GEN-LAST:event_btnDeleteProdActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductSearchActionPerformed

    }//GEN-LAST:event_txtProductSearchActionPerformed

    private void txtProductSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductSearchKeyReleased
        search();
    }//GEN-LAST:event_txtProductSearchKeyReleased

    private void btnUpdateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProdActionPerformed

        btnDeleteProd.setEnabled(false);
        btnUpdateProd.setEnabled(false);
        btnSaveUpdate.setEnabled(true);
        txtId.setEditable(false);
        enableTxtFields();

    }//GEN-LAST:event_btnUpdateProdActionPerformed

    private void tblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchMouseClicked
        setFields();
        if (!txtCode.getText().isEmpty()) {
            btnDeleteProd.setEnabled(true);
            btnUpdateProd.setEnabled(true);
            btnClearFields.setEnabled(true);
        }
    }//GEN-LAST:event_tblSearchMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        JOptionPane.showInternalMessageDialog(null, "This field cant be changed");

    }//GEN-LAST:event_txtNameActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        search();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnDeleteProd;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSaveUpdate;
    private javax.swing.JButton btnUpdateProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtManufactor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtProductSearch;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables

    public void search() {

        try {
            String name = txtProductSearch.getText();
            ProductModel productmodel = new ProductModel();
            productmodel.setName(name);

            ProductControler productCont = new ProductControler(productmodel);
            productCont.search(productmodel);

            tblSearch.setModel(DbUtils.resultSetToTableModel(productCont.rs));

        } catch (SQLException ex) {
            Logger.getLogger(SearchProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setFields() {
        int set = tblSearch.getSelectedRow();
        txtId.setText(tblSearch.getModel().getValueAt(set, 0).toString());
        txtCode.setText(tblSearch.getModel().getValueAt(set, 1).toString());
        txtName.setText(tblSearch.getModel().getValueAt(set, 2).toString());
        txtType.setText(tblSearch.getModel().getValueAt(set, 3).toString());
        txtManufactor.setText(tblSearch.getModel().getValueAt(set, 4).toString());
        txtBarcode.setText(tblSearch.getModel().getValueAt(set, 5).toString());
        txtAmount.setText(tblSearch.getModel().getValueAt(set, 6).toString());

    }

    private void refresh() {

        try {
            ProductControler productCont = new ProductControler();
            ProductModel productModel = new ProductModel();

            DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
            model.setNumRows(0);

            ArrayList<ProductModel> list = productCont.read();

            for (int i = 0; i < list.size(); i++) {
                model.addRow(new Object[]{
                    list.get(i).getIdProducts(),
                    list.get(i).getCode(),
                    list.get(i).getName(),
                    list.get(i).getType(),
                    list.get(i).getManufactor(),
                    list.get(i).getBarCode(),
                    list.get(i).getAmount(),});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "tela principal" + e);
        }
    }

    private void clearFields() {
        txtProductSearch.setText(null);
        txtId.setText(null);
        txtCode.setText(null);
        txtName.setText(null);
        txtType.setText(null);
        txtManufactor.setText(null);
        txtBarcode.setText(null);
        txtAmount.setText(null);
        // cmbPerfil.setSelectedItem(0);
    }

    private void disableButtons() {
        btnDeleteProd.setEnabled(false);
        btnSaveUpdate.setEnabled(false);
        btnUpdateProd.setEnabled(false);
        btnClearFields.setEnabled(false);
    }

    private void disableTxtFields() {
        txtId.setEnabled(false);
        txtCode.setEnabled(false);
        txtName.setEnabled(false);
        txtType.setEnabled(false);
        txtManufactor.setEnabled(false);
        txtBarcode.setEnabled(false);
        txtAmount.setEnabled(false);
    }

    private void enableTxtFields() {
        txtId.setEnabled(true);
        txtCode.setEnabled(true);
        txtName.setEnabled(true);
        txtType.setEnabled(true);
        txtManufactor.setEnabled(true);
        txtBarcode.setEnabled(true);
        txtAmount.setEnabled(true);
        tblSearch.setEnabled(false);
    }

    private void update() {
        int id = parseInt(txtId.getText());
        String code = txtCode.getText();
        String name = txtName.getText();
        String type = txtType.getText();
        String Manufactor = txtManufactor.getText();
        String barcode = txtBarcode.getText();
        int amount = parseInt(txtAmount.getText());

        //  String perfil = cmbPerfil.getSelectedItem().toString();
        ProductModel productmodel = new ProductModel();
        productmodel.setIdProducts(id);
        productmodel.setCode(code);
        productmodel.setName(name);
        productmodel.setType(type);
        productmodel.setManufactor(Manufactor);
        productmodel.setBarCode(barcode);
        productmodel.setAmount(amount);

        ProductControler productCont = new ProductControler(productmodel);
        productCont.update(productmodel);

    }

    private void delete() {

        int i = JOptionPane.showConfirmDialog(null, "Do you really want to delete the user (" + txtName.getText() + ")?", "Warning", JOptionPane.OK_CANCEL_OPTION, 2);

        if (i == JOptionPane.OK_OPTION) {
            int id = Integer.parseInt(txtId.getText());

            ProductModel productmodel = new ProductModel();
            productmodel.setIdProducts(id);

            ProductControler productCont = new ProductControler(productmodel);
            productCont.delete(productmodel);
            clearFields();
            disableButtons();

            refresh();

        } else {
            //clearFields();
            // btnDeleteUser.setEnabled(false);
            btnUpdateProd.setEnabled(false);
        }
    }

    private void autorizationUser() {

        String autPassword = JOptionPane.showInputDialog(null, "Insert your autorization pin", "Acess verification", 3);
        String user = MainFrame.lblUsuario.getText();

        try {

            UserModel usermodel = new UserModel();
            usermodel.setUser(user);
            usermodel.setAutPassword(autPassword);

            UserControler userCont = new UserControler(usermodel);
            ResultSet rs = userCont.autorizationUser(usermodel);

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Verified", "Authorized user", 1);
                delete();

            } else {
                JOptionPane.showMessageDialog(null, "Wrong pin", "User not authorized", 0);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "acesso negado");
        }
    }

    public void setNameEdit(String a) {
        txtProductSearch.setText(a);
    }

}
