package VIEW.requests;

import CONTROLER.ProductControler;
import MODEL.ProductModel;
import VIEW.productViews.SearchProducts;
import VIEW.requesterViews.InsertRequester;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class RequestForm extends javax.swing.JInternalFrame {

    public RequestForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblReaquestNumber = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDateActual = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnInsertRequest = new javax.swing.JButton();
        txtCodeRequester = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtProductCodeSearch = new javax.swing.JTextField();
        txtProductSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSetCode = new javax.swing.JTextField();
        txtSetName = new javax.swing.JTextField();
        txtSetUnity = new javax.swing.JTextField();
        txtSetAmount = new javax.swing.JTextField();
        txtSetQtdRequest = new javax.swing.JTextField();
        btnInsertProducts = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductList = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Request");
        setPreferredSize(new java.awt.Dimension(1100, 720));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblReaquestNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jLabel9.setText("REQ NUMERO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        lblDateActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblDateActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        lblDate.setText("DATE");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        btnInsertRequest.setText("Insert requester");
        btnInsertRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertRequestActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        txtCodeRequester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeRequesterActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodeRequester, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 87, -1));

        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel12.setText("Code");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel11.setText("REQUESTER INFORMATIONS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("Search by code");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, -1, -1));

        jRadioButton2.setText("Search by name");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(txtProductCodeSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 42, 75, -1));

        txtProductSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtProductSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 73, 664, -1));

        jLabel1.setText("Code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel3.setText("Unt");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, -1, -1));

        jLabel4.setText("Qtd est");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel5.setText("Qtd req");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, -1, -1));
        jPanel1.add(txtSetCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 49, -1));
        jPanel1.add(txtSetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 562, -1));

        txtSetUnity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetUnityActionPerformed(evt);
            }
        });
        jPanel1.add(txtSetUnity, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 40, -1));
        jPanel1.add(txtSetAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 50, -1));
        jPanel1.add(txtSetQtdRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 60, -1));

        btnInsertProducts.setText("Insert");
        btnInsertProducts.setEnabled(false);
        btnInsertProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertProductsActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearch);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1044, 90));

        jButton2.setText("SAVE");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, -1, -1));

        jButton4.setText("SAIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        jLabel13.setText("PRODUCTS INFORMATIONS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        tblProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Product", "Unity", "ResquestAmount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(tblProductList);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1040, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1064, 580));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtSetUnityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetUnityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetUnityActionPerformed

    private void txtCodeRequesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeRequesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeRequesterActionPerformed

    private void txtProductSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductSearchKeyReleased
        search();

    }//GEN-LAST:event_txtProductSearchKeyReleased

    private void tblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchMouseClicked
        setFields();
        btnInsertProducts.setEnabled(true);
    }//GEN-LAST:event_tblSearchMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Date data = new Date();
        DateFormat format = DateFormat.getDateInstance(DateFormat.SHORT);
        lblDateActual.setText(format.format(data));

    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnInsertProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertProductsActionPerformed

        try {
            if (Integer.parseInt(txtSetAmount.getText()) == 0 || Integer.parseInt(txtSetQtdRequest.getText()) > Integer.parseInt(txtSetAmount.getText())) {

                JOptionPane.showMessageDialog(null, "Insufficient amount in stock");

            } else if (Integer.parseInt(txtSetQtdRequest.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "Enter a value for quantity");

            } else {
                setProductTable();
                btnInsertProducts.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a value for quantity");
        }
    }//GEN-LAST:event_btnInsertProductsActionPerformed

    private void btnInsertRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertRequestActionPerformed
        InsertRequester insertRequester = new InsertRequester();
        getParent().add(insertRequester);
        insertRequester.setVisible(true);
    }//GEN-LAST:event_btnInsertRequestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertProducts;
    private javax.swing.JButton btnInsertRequest;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateActual;
    private javax.swing.JLabel lblReaquestNumber;
    private javax.swing.JTable tblProductList;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtCodeRequester;
    private javax.swing.JTextField txtProductCodeSearch;
    private javax.swing.JTextField txtProductSearch;
    private javax.swing.JTextField txtSetAmount;
    private javax.swing.JTextField txtSetCode;
    private javax.swing.JTextField txtSetName;
    private javax.swing.JTextField txtSetQtdRequest;
    private javax.swing.JTextField txtSetUnity;
    // End of variables declaration//GEN-END:variables

    private void search() {
        try {
            String name = txtProductSearch.getText();
            ProductModel productmodel = new ProductModel();
            productmodel.setName(name);

            ProductControler productCont = new ProductControler(productmodel);
            productCont.search(productmodel);

            tblSearch.setModel(DbUtils.resultSetToTableModel(productCont.rs));

            txtSetCode.setEditable(false);
            txtSetName.setEditable(false);
            txtSetUnity.setEditable(false);
            txtSetAmount.setEditable(false);

        } catch (SQLException ex) {
            Logger.getLogger(SearchProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setFields() {
        int set = tblSearch.getSelectedRow();
        txtSetName.setText(tblSearch.getModel().getValueAt(set, 2).toString());
        txtSetCode.setText(tblSearch.getModel().getValueAt(set, 1).toString());
        txtSetUnity.setText(tblSearch.getModel().getValueAt(set, 6).toString());
        txtSetAmount.setText(tblSearch.getModel().getValueAt(set, 7).toString());
        txtSetQtdRequest.setText("0");
        txtSetQtdRequest.requestFocus();
    }

    private void setProductTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblProductList.getModel();
        dtm.addRow(new Object[]{txtSetCode.getText(), txtSetName.getText(), txtSetUnity.getText(), txtSetQtdRequest.getText()});
        txtSetCode.setText(null);
        txtSetName.setText(null);
        txtSetUnity.setText(null);
        txtSetAmount.setText(null);
        txtSetQtdRequest.setText(null);
    }
}
